# Generated by Django 3.0.7 on 2020-06-16 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fixture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('opposition', models.CharField(default=None, max_length=100)),
                ('home_away', models.CharField(choices=[('Home', 'Home'), ('Away', 'Away')], max_length=5)),
                ('venue', models.CharField(default=None, max_length=100)),
                ('competition', models.CharField(choices=[('League', 'League'), ('Cup', 'Cup'), ('Friendly', 'Friendly')], max_length=10)),
                ('formation', models.CharField(choices=[('4-4-2', '4-4-2'), ('4-3-3', '4-3-3'), ('4-5-1', '4-5-1'), ('5-3-2', '5-3-2')], max_length=10)),
                ('instructions', models.TextField(default=None, max_length=3000)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Club')),
                ('selected_team', models.ManyToManyField(default=None, related_name='selected_team', to='account.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerAvailability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('availability', models.CharField(choices=[('Unknown', 'Unknown'), ('Available', 'Available'), ('Not Available', 'Not Available'), ('Maybe Available', 'Maybe Available')], default='Unknown', max_length=20)),
                ('fixture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.Fixture')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Profile')),
            ],
        ),
    ]
