# Generated by Django 3.0.7 on 2020-06-17 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0002_auto_20200616_1012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fixture',
            name='formation',
        ),
        migrations.RemoveField(
            model_name='fixture',
            name='instructions',
        ),
        migrations.AlterField(
            model_name='playeravailability',
            name='availability',
            field=models.CharField(choices=[('Not Set', 'Not Set'), ('Available', 'Available'), ('Not Available', 'Not Available'), ('Maybe Available', 'Maybe Available')], default='Not Set', max_length=20),
        ),
    ]
