# Generated by Django 3.0.7 on 2020-06-17 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('club', '0003_auto_20200617_1140'),
    ]

    operations = [
        migrations.CreateModel(
            name='PositionAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('Goalkeeper', 'Goalkeeper'), ('Defender', 'Defender'), ('Midfielder', 'Midfielder'), ('Attacker', 'Attacker'), ('Substitute', 'Substitute'), ('Not Set', 'Not Set')], default='Not Set', max_length=20)),
                ('fixture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.Fixture')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Profile')),
            ],
        ),
    ]
