# Generated by Django 3.0.7 on 2020-06-17 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0005_playerperformance_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerperformance',
            name='appearances',
            field=models.IntegerField(default=1),
        ),
    ]
