# Generated by Django 3.0.7 on 2020-06-17 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0006_playerperformance_appearances'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerperformance',
            name='red_cards',
        ),
        migrations.RemoveField(
            model_name='playerperformance',
            name='yellow_cards',
        ),
    ]
