# Generated by Django 3.0.6 on 2020-06-01 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='birth_date',
        ),
    ]
