# Generated by Django 3.0.7 on 2020-06-16 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(default=None, max_length=100)),
                ('content', models.TextField(default=None, max_length=3000)),
                ('status', models.TextField(choices=[('Unread', 'Unread'), ('Read', 'Read')], default='Unread', max_length=100)),
                ('time', models.DateField(auto_now=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='account.Profile')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='account.Profile')),
            ],
        ),
    ]
