# Generated by Django 3.0.6 on 2020-05-24 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('film_app', '0003_auto_20200524_1638'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='director',
            name='film',
        ),
        migrations.AddField(
            model_name='film',
            name='director',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='film_app.Director'),
        ),
    ]
