# Generated by Django 3.0.6 on 2020-05-24 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('film_app', '0004_auto_20200524_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='director',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='film_app.Director'),
        ),
    ]
