# Generated by Django 3.0.6 on 2020-05-21 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalrate',
            name='daily_rate',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='real_cost',
            field=models.IntegerField(),
        ),
    ]
