# Generated by Django 3.0.7 on 2020-06-16 06:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default=None, max_length=30, null=True)),
                ('last_name', models.CharField(default=None, max_length=30, null=True)),
                ('role', models.CharField(choices=[('Manager', 'Manager'), ('Player', 'Player'), ('Player-Manager', 'Player-Manager')], default=None, max_length=20, null=True)),
                ('position', models.CharField(choices=[('Goalkeeper', 'Goalkeeper'), ('Defender', 'Defender'), ('Midfielder', 'Midfielder'), ('Attacker', 'Attacker')], default=None, max_length=12, null=True)),
                ('email', models.EmailField(default=None, max_length=254, null=True)),
                ('phone', models.IntegerField(default=None, null=True)),
                ('image', models.ImageField(default='gallery/football.png', null=True, upload_to='gallery')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=50)),
                ('logo', models.ImageField(null=True, upload_to='')),
                ('password', models.CharField(max_length=20)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manager', to='account.Profile')),
                ('players', models.ManyToManyField(to='account.Profile')),
            ],
        ),
    ]
